
-- Deseja-se uma lista de todos os funcionários que trabalham no mesmo
-- departamento do BRUNO AZEVEDO.

SELECT *
FROM FUNC F1
WHERE F1.CD_DEPTO = (SELECT F2.CD_DEPTO
                    FROM FUNC F2
                    WHERE F2.NM_FUNC || F2.NM_SOBRENOME = 'BRUNOAZEVEDO');


SELECT F1.CD_MAT AS MATRICULA,
       F1.NM_FUNC || ' ' || F1.NM_SOBRENOME AS FUNCIONARIO,
       (SELECT G.NM_FUNC 
        FROM FUNC G INNER JOIN DEPTO 
        ON G.CD_MAT = DEPTO.CD_GERENTE 
              AND G.CD_DEPTO = F1.CD_DEPTO
              AND G.CD_MAT != F1.CD_MAT) AS GERENTE,
       (SELECT DEPTO.NM_DEPTO 
        FROM DEPTO 
        WHERE DEPTO.CD_DEPTO = F1.CD_DEPTO) AS DEPARTAMENTO,
       F1.NR_RAMAL AS RAMAL,
       F1.NR_CARGO AS NUMERO_CARGO,
       TO_CHAR(F1.VL_SAL, 'L999G990D00') AS SALARIO,
       TO_CHAR(F1.DT_ADM, 'DD/MM/YYYY') AS DATA_ADMISSAO,
       TO_CHAR(F1.DT_NASC, 'DD/MM/YYYY') AS DATA_NASCIMENTO,       
       F1.NR_GIT AS GIT,
       REPLACE(REPLACE(F1.IN_SEXO, 'M', 'MASCULINO'), 'F', 'FEMININO') AS SEXO
FROM FUNC F1
WHERE F1.CD_DEPTO = (SELECT F2.CD_DEPTO
                    FROM FUNC F2
                    WHERE F2.NM_FUNC || F2.NM_SOBRENOME = 'BRUNOAZEVEDO')
ORDER BY 2;