
-- Deseja-se uma lista contendo nome, sobrenome, matrícula, ramal;
-- código e nome do departamento;
-- código e nome do projeto de todos os funcionários que sejam responsáveis de projeto;
-- mas não são gerentes de departamento.


--    (SELECT PROJ.CD_PROJ
--    FROM PROJ
--    WHERE PROJ.CD_DEPTO = FUNCIONARIO.CD_DEPTO
--         AND PROJ.CD_RESP = FUNCIONARIO.CD_MAT
--         AND ) AS CODIGO_PROJETO


SELECT FUNCIONARIO.NM_FUNC || ' ' || FUNCIONARIO.NM_SOBRENOME AS NOME_COMPLETO,
       FUNCIONARIO.CD_MAT AS MATRICULA,
       FUNCIONARIO.NR_RAMAL AS RAMAL,
       FUNCIONARIO.CD_DEPTO AS CODIGO_DEPARTAMENTO,
       (SELECT DEPTO.NM_DEPTO
        FROM DEPTO
        WHERE DEPTO.CD_DEPTO = FUNCIONARIO.CD_DEPTO) AS NOME_DEPARTAMENTO,
        PROJETO.CD_PROJ AS CODIGO_PROJETO,
        PROJETO.NM_PROJ AS NOME_PROJETO

FROM FUNC FUNCIONARIO INNER JOIN PROJ PROJETO

ON PROJETO.CD_DEPTO = FUNCIONARIO.CD_DEPTO
    AND PROJETO.CD_RESP = FUNCIONARIO.CD_MAT
    AND FUNCIONARIO.CD_MAT NOT IN (SELECT NVL(DEPARTAMENTO.CD_GERENTE, 0)
                                   FROM DEPTO DEPARTAMENTO);