
-- Crie uma consulta que retornará as médias salariais máxima e mínima agrupadas por 
-- departamento da tabela employees.

SELECT E.DEPARTMENT_ID,
       TO_CHAR(MAX(E.SALARY), 'L999G990D00') AS MAX_SALARY_EMP,
       TO_CHAR(MIN(E.SALARY), 'L999G990D00') AS MIN_SALARY_EMP
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IS NOT NULL
GROUP BY E.DEPARTMENT_ID
ORDER BY E.DEPARTMENT_ID DESC;


SELECT DEPARTMENT_ID, D.DEPARTMENT_NAME,
       TO_CHAR(MAX(E.SALARY), 'L999G990D00') AS MAX_SALARY_EMP,
       TO_CHAR(MIN(E.SALARY), 'L999G990D00') AS MIN_SALARY_EMP
FROM EMPLOYEES E JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY DEPARTMENT_ID DESC, D.DEPARTMENT_NAME;
