
-- Deseja-se uma lista contendo o código e nome de cada departamento, nome e
-- sobrenome do gerente, ordenado por código de departamento.

SELECT DEPARTAMENTOS.CD_DEPTO AS CODIGO_DEPARTAMENTOS,
       DEPARTAMENTOS.NM_DEPTO AS NOME_DEPARTAMENTOS,
       FUNCIONARIOS.NM_FUNC || ' ' || FUNCIONARIOS.NM_SOBRENOME AS NOME_COMPLETO
FROM DEPTO DEPARTAMENTOS, FUNC FUNCIONARIOS
WHERE DEPARTAMENTOS.CD_GERENTE = FUNCIONARIOS.CD_MAT
