
-- Deseja-se uma lista contendo nome, sobrenome, salário e nome do departamento
-- de todos os funcionários que sejam responsáveis por projeto.

SELECT FUNCIONARIOS.NM_FUNC AS NOMES,
       FUNCIONARIOS.NM_SOBRENOME AS SOBRENOMES,
       FUNCIONARIOS.VL_SAL AS SALARIOS,
       DEPARTAMENTOS.NM_DEPTO AS DEPARTAMENTOS
FROM FUNC FUNCIONARIOS, DEPTO DEPARTAMENTOS, PROJ PROJETOS
WHERE FUNCIONARIOS.CD_MAT = PROJETOS.CD_RESP
      AND FUNCIONARIOS.CD_DEPTO = DEPARTAMENTOS.CD_DEPTO;
