
-- Exiba o nome dos departamentos e o nome do seu respectivo departamento
-- contábil (cd_depto_ctb)


SELECT DEPARTAMENTOS.NM_DEPTO AS NOME_DEPARTAMENTOS,
       CONTABILIDADES.NM_DEPTO AS NOME_CONTABILIDADES
FROM DEPTO DEPARTAMENTOS INNER JOIN DEPTO CONTABILIDADES
     ON (DEPARTAMENTOS.CD_DEPTO_CTB = CONTABILIDADES.CD_DEPTO);